# Generated by Django 6.1 on 2026-09-09 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_experience_category_experience_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='experience',
            name='started_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
