# Generated by Django 6.1 on 2026-09-14 00:30

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_experience_started_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('institution_name', models.CharField(max_length=255)),
                ('starting_year', models.DateTimeField(blank=True, null=True)),
                ('end_year', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
