# Generated by Django 6.1 on 2026-09-14 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_education'),
    ]

    operations = [
        migrations.AddField(
            model_name='education',
            name='description',
            field=models.TextField(default='', max_length=400),
        ),
    ]
