# Generated by Django 6.1 on 2026-09-14 09:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_education_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education',
            name='end_year',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(2010), django.core.validators.MaxValueValidator(2100)]),
        ),
        migrations.AlterField(
            model_name='education',
            name='starting_year',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(2010), django.core.validators.MaxValueValidator(2100)]),
        ),
    ]
